/// SAIE — ConversationController
///
/// Orchestrates the complete conversation lifecycle.
/// Handles each route dispatched by the [ConversationRouter]:
///   - continueAssessment   → runs Answer Intelligence + Assessment Engine
///   - academicDiscussion   → answers academic question, returns to assessment
///   - recommendationDiscussion → answers questions about the recommendation
///   - clarification        → explains, repeats question
///   - greeting / goodbye   → appropriate response
///   - skipQuestion         → skips, asks next
///   - restartAssessment    → resets assessment state
///   - unknown / help       → polite redirect
///
/// The controller is purely functional: it takes a [ConversationContext] and
/// returns an updated [ControllerResult]. No state is held internally.
library;

import 'package:stustep/features/saie/analysis/answer_intelligence_engine.dart';
import 'package:stustep/features/saie/assessment/adaptive_assessment_engine.dart';
import 'package:stustep/features/saie/analysis/answer_completion_context.dart';
import 'package:stustep/features/saie/analysis/answer_completion_evaluation.dart';
import 'package:stustep/features/saie/analysis/answer_completion_evaluator.dart';

import 'package:stustep/features/saie/assessment/assessment_controller.dart';
import 'package:stustep/features/saie/assessment/assessment_state.dart';
import 'package:stustep/features/saie/assessment/question_history.dart';
import 'package:stustep/features/saie/conversation/conversation_context.dart' as conv;
import 'package:stustep/features/saie/conversation/conversation_event.dart';
import 'package:stustep/features/saie/conversation/conversation_history.dart';
import 'package:stustep/features/saie/conversation/conversation_language.dart';
import 'package:stustep/features/saie/conversation/conversation_memory.dart';
import 'package:stustep/features/saie/conversation/conversation_phase.dart';
import 'package:stustep/features/saie/conversation/conversation_router.dart';
import 'package:stustep/features/saie/conversation/conversation_summary.dart';
import 'package:stustep/features/saie/core/enums.dart';
import 'package:stustep/features/saie/decision/conversation_context.dart' as dec;
import 'package:stustep/features/saie/explainable/explainable_ai_engine.dart';
import 'package:stustep/features/saie/llm/llm_explanation_service.dart';
import 'package:stustep/features/saie/llm/qul_intent.dart';
import 'package:stustep/features/saie/matching/major_matching_engine.dart';
import 'package:stustep/features/saie/models/assessment_goal.dart';
import 'package:stustep/features/saie/models/major.dart';
import 'package:stustep/features/saie/models/question.dart';
import 'package:stustep/features/saie/profile/student_cognitive_profile.dart';
import 'package:stustep/features/saie/recommendation/recommendation_engine.dart';
import 'package:stustep/features/saie/recommendation/recommendation_report.dart';
import 'package:uuid/uuid.dart';

// ─────────────────────────────────────────────────────────────────────────────
// ControllerResult
// ─────────────────────────────────────────────────────────────────────────────

/// The immutable output of one [ConversationController] turn.
final class ControllerResult {
  /// The response text to send back to the student.
  final String response;

  /// Updated memory after this turn.
  final ConversationMemory updatedMemory;

  /// Updated phase after this turn.
  final ConversationPhase updatedPhase;

  /// Updated language state.
  final ConversationLanguage updatedLanguage;

  /// Updated student profile (may be unchanged).
  final StudentCognitiveProfile updatedProfile;

  /// The event generated by this turn.
  final ConversationEvent event;

  /// Whether the assessment advanced this turn.
  final bool assessmentAdvanced;

  /// Whether a recommendation was generated this turn.
  final bool recommendationGenerated;

  const ControllerResult({
    required this.response,
    required this.updatedMemory,
    required this.updatedPhase,
    required this.updatedLanguage,
    required this.updatedProfile,
    required this.event,
    required this.assessmentAdvanced,
    required this.recommendationGenerated,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// ConversationController
// ─────────────────────────────────────────────────────────────────────────────

/// Routes each turn to the correct handler and assembles a [ControllerResult].
final class ConversationController {
  final AnswerIntelligenceEngine _answerEngine;
  final AnswerCompletionEvaluator _completionEvaluator;
  final AdaptiveAssessmentEngine _assessmentEngine;
  final AssessmentController _assessmentController;
  final MajorMatchingEngine _matchingEngine;
  final RecommendationEngine _recommendationEngine;
  final ExplainableAIEngine _explainableEngine;
  final LLMExplanationService _explanationService;
  final List<Major> _allMajors;
  final List<Question> _allQuestions;

  static const _uuid = Uuid();

  ConversationController({
    required AnswerIntelligenceEngine answerEngine,
    required AdaptiveAssessmentEngine assessmentEngine,
    AnswerCompletionEvaluator completionEvaluator =
        const AnswerCompletionEvaluator(),
    required AssessmentController assessmentController,
    required MajorMatchingEngine matchingEngine,
    required RecommendationEngine recommendationEngine,
    required ExplainableAIEngine explainableEngine,
    required LLMExplanationService explanationService,
    required List<Major> allMajors,
    required List<Question> allQuestions,
  })  : _answerEngine = answerEngine,
        _completionEvaluator = completionEvaluator,
        _assessmentEngine = assessmentEngine,
        _assessmentController = assessmentController,
        _matchingEngine = matchingEngine,
        _recommendationEngine = recommendationEngine,
        _explainableEngine = explainableEngine,
        _explanationService = explanationService,
        _allMajors = allMajors,
        _allQuestions = allQuestions;

  // ── Primary dispatch ───────────────────────────────────────────────────────

  /// Handles a single conversation turn and returns a [ControllerResult].
  ///
  /// Async because QUL handlers may call [LLMExplanationService] which
  /// performs a network request (with timeout + local fallback).
  Future<ControllerResult> handle({
    required conv.ConversationContext context,
    required RouteDecision routeDecision,
  }) async {
    return switch (routeDecision.route) {
      ConversationRoute.continueAssessment =>
        _handleContinueAssessment(context),
      ConversationRoute.academicDiscussion =>
        _handleAcademicDiscussion(context, routeDecision),
      ConversationRoute.recommendationDiscussion =>
        _handleRecommendationDiscussion(context),
      ConversationRoute.clarification =>
        _handleClarification(context),
      ConversationRoute.greeting =>
        _handleGreeting(context),
      ConversationRoute.help =>
        _handleHelp(context),
      ConversationRoute.skipQuestion =>
        _handleSkipQuestion(context),
      ConversationRoute.restartAssessment =>
        _handleRestartAssessment(context),
      ConversationRoute.goodbye =>
        _handleGoodbye(context),
      // ── Question Understanding Layer routes ───────────────────────────────
      ConversationRoute.wordMeaning =>
        _handleWordMeaning(context),
      ConversationRoute.uncertainty =>
        _handleUncertainty(context),
      ConversationRoute.whyThisQuestion =>
        _handleWhyThisQuestion(context),
      ConversationRoute.alternativeQuestion =>
        _handleAlternativeQuestion(context),
      ConversationRoute.questionExamples =>
        _handleQuestionExamples(context),
      ConversationRoute.unknown =>
        _handleUnknown(context),
    };
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Route Handlers
  // ─────────────────────────────────────────────────────────────────────────

  ControllerResult _handleContinueAssessment(conv.ConversationContext context) {
    final currentState = context.memory.assessmentState;
    final activeQuestion = context.activeQuestion;

    // Start assessment if it has not begun.
    if (currentState == null) {
      return _startAssessment(context);
    }

    // ── Conversation Completion Guard ─────────────────────────────────────
    // If there is an unresolved student need, address it before allowing
    // assessment to advance. This prevents the assessment from continuing
    // while the student still has an open question.
    if (context.phase.hasUnresolvedNeed) {
      return _resolvePendingNeed(context);
    }

    // No pending question but assessment is in progress → re-deliver the active
    // question from the current state (handles "التالي", "كمل", "واصل").
    if (activeQuestion == null) {
      final nextQ = currentState.activeQuestion;
      final response = nextQ != null
          ? _tr(context,
              ar: 'تفضل، إليك السؤال:\n\n${_formatQuestion(nextQ, context)}',
              en: 'Here is the next question:\n\n${_formatQuestion(nextQ, context)}')
          : _tr(context,
              ar: 'لقد أنهيت جميع الأسئلة. جارٍ إعداد توصياتك...',
              en: 'You have completed all questions. Preparing your recommendations...');

      final updatedMemory = _updateMemory(
        context: context,
        updatedState: currentState,
        phase: context.phase,
      );

      return ControllerResult(
        response: response,
        updatedMemory: updatedMemory,
        updatedPhase: context.phase,
        updatedLanguage: context.language,
        updatedProfile: context.profile,
        event: _event(nextQ != null
            ? ConversationEventType.questionAsked
            : ConversationEventType.engineResponse),
        assessmentAdvanced: false,
        recommendationGenerated: false,
      );
    }

    // Process the answer through the Answer Intelligence Engine.
    final decCtx = _buildDecisionContext(context, currentState);
    final processingResult = _answerEngine.process(
      rawAnswer: context.studentMessage,
      activeQuestion: activeQuestion,
      profile: context.profile,
      context: decCtx,
      decisionResult: context.decision,
      history: currentState.answerHistory,
    );

    // ── Answer Completion Gate ─────────────────────────────────────────
    // The assessment MUST NOT advance until the evaluator confirms the
    // current question has been answered sufficiently.
    //
    // The gate reads exclusively from already-computed data (features, score)
    // — it performs no additional NLP or scoring.
    if (processingResult.features != null && processingResult.score != null) {
      final completionCtx = AnswerCompletionContext.build(
        question: activeQuestion,
        rawAnswer: context.studentMessage,
        features: processingResult.features!,
        score: processingResult.score!,
        recentHistory: context.memory.contextWindow(context.policy),
        clarificationsOnThisQuestion: context.phase.clarificationCount,
        language: context.language.active,
      );

      final evaluation = _completionEvaluator.evaluate(completionCtx);

      if (!evaluation.allowsAdvancement) {
        return _handleIncompleteAnswer(
          context: context,
          evaluation: evaluation,
          activeQuestion: activeQuestion,
          currentState: currentState,
        );
      }
    }

    // ── Advance the assessment (gate approved) ────────────────────────────
    // Reconstruct the full QuestionHistory from the current AssessmentState so
    // QuestionSelector sees ALL previously asked questions — not just this turn.
    final turnResult = _assessmentEngine.advance(
      currentState: currentState,
      processingResult: processingResult,
      questionHistory: _buildQuestionHistory(currentState),
      allQuestions: _allQuestions,
      context: decCtx,
    );

    final updatedState = turnResult.updatedState;
    final updatedProfile =
        processingResult.updatedProfile ?? context.profile;

    // Check if assessment completed → trigger recommendation.
    if (turnResult.assessmentCompleted) {
      return _generateRecommendation(
        context: context,
        updatedState: updatedState,
        updatedProfile: updatedProfile,
        stats: turnResult.statistics,
      );
    }

    // Build response for next question.
    final nextQ = turnResult.nextQuestion;
    final response = nextQ == null
        ? _tr(context,
            ar: 'شكراً على إجابتك. هل تريد مواصلة التقييم؟',
            en: 'Thank you for your answer. Shall we continue the assessment?')
        : _formatQuestion(nextQ, context);

    final updatedMemory = _updateMemory(
      context: context,
      updatedState: updatedState,
      phase: context.phase,
    );

    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: context.phase,
      updatedLanguage: context.language,
      updatedProfile: updatedProfile,
      event: _event(ConversationEventType.questionAnswered,
          intent: context.decision.detectedIntent.name),
      assessmentAdvanced: true,
      recommendationGenerated: false,
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Answer Completion Gate — Incomplete Answer Handler
  // ─────────────────────────────────────────────────────────────────────────

  /// Called when [AnswerCompletionEvaluator] returns a non-advancing result.
  ///
  /// Branches on [CompletionReason] (the extensible inner layer):
  ///   - Re-routes to QUL/meta handlers when the message is not an answer.
  ///   - Builds a targeted probe response for partial/insufficient answers.
  ///   - Repeats the question after every non-advancing response so the
  ///     student always has the question in view.
  ///
  /// The assessment NEVER advances from this method.
  ControllerResult _handleIncompleteAnswer({
    required conv.ConversationContext context,
    required CompletionEvaluation evaluation,
    required Question activeQuestion,
    required AssessmentState currentState,
  }) {
    switch (evaluation.reason) {
      // ─ Re-route to existing QUL infrastructure ───────────────────────────────

      case CompletionReason.clarificationRequest:
        // The message is a question. Route to the clarification handler
        // which will explain and re-present the assessment question.
        return _simple(
          context: context,
          response: _tr(context,
              ar: 'فهمت سؤالك. '
                  '${_tr(context, ar: "لنفس السؤال", en: "For the same question")} — '
                  '${_formatQuestion(activeQuestion, context)}',
              en: 'I understand your question. '
                  'For the same question — '
                  '${_formatQuestion(activeQuestion, context)}'),
          eventType: ConversationEventType.questionExplained,
          assessmentAdvanced: false,
        );

      case CompletionReason.metaQuestion:
        // The student is asking about the assessment itself.
        // Acknowledge, then re-present the question.
        final metaAr = 'سؤال وجيه — هذا التقييم يساعدني أن أفهم ميولك وقدراتك'
            ' لأقترح عليك التخصص الأنسب.'
            ' لا توجد إجابة خاطئة هنا.'
            '\n\n${_formatQuestion(activeQuestion, context)}';
        final metaEn = 'Good question — this assessment helps me understand'
            ' your strengths and interests so I can suggest the most'
            ' suitable major for you.'
            ' There are no right or wrong answers.'
            '\n\n${_formatQuestion(activeQuestion, context)}';
        return _simple(
          context: context,
          response: _tr(context, ar: metaAr, en: metaEn),
          eventType: ConversationEventType.questionExplained,
          assessmentAdvanced: false,
        );

      // ─ Probe responses (assessment does NOT advance) ─────────────────────

      case CompletionReason.insufficientContent:
        // The answer has too little content to evaluate.
        // Build a targeted, question-type-aware gap message.
        final probe = _tr(context,
            ar: 'شكراً لإجابتك. ${evaluation.gap ?? "هل يمكنك توضيح إجابتك قليلاً؟"}\n\n${_formatQuestion(activeQuestion, context)}',
            en: 'Thank you. ${evaluation.gap ?? "Could you clarify your answer a little?"}\n\n${_formatQuestion(activeQuestion, context)}');
        return _simple(
          context: context,
          response: probe,
          eventType: ConversationEventType.questionExplained,
          assessmentAdvanced: false,
        );

      case CompletionReason.partialAnswer:
      case CompletionReason.lowEvaluatorConfidence:
        // The answer is a start but needs more depth, OR the evaluator
        // was not confident enough. Both get one probe turn.
        final probe = _tr(context,
            ar: 'شكراً. ${evaluation.gap ?? "هل يمكنك إخباري أكثر قليلاً؟"}\n\n${_formatQuestion(activeQuestion, context)}',
            en: 'Thank you. ${evaluation.gap ?? "Could you tell me a little more?"}\n\n${_formatQuestion(activeQuestion, context)}');
        // Mark this as a clarification turn so the NEXT message from the student
        // is accepted as a complete answer regardless of its content.
        // This prevents an infinite probe loop.
        final updatedPhase = context.phase.addClarification();
        final updatedMemory = _updateMemory(
          context: context,
          updatedState: currentState,
          phase: updatedPhase,
        );
        return ControllerResult(
          response: probe,
          updatedMemory: updatedMemory,
          updatedPhase: updatedPhase,
          updatedLanguage: context.language,
          updatedProfile: context.profile,
          event: _event(ConversationEventType.questionExplained),
          assessmentAdvanced: false,
          recommendationGenerated: false,
        );

      case CompletionReason.accepted:
        // Unreachable — accepted only appears with CompletionState.complete,
        // which is handled before _handleIncompleteAnswer is called.
        throw StateError(
            'CompletionReason.accepted reached _handleIncompleteAnswer. '
            'This is a bug in AnswerCompletionEvaluator.');
    }
  }

  ControllerResult _startAssessment(conv.ConversationContext context) {
    // Use _assessmentEngine.begin() — not _assessmentController.start().
    // begin() selects the first question via the question selector.
    // _assessmentController.start() only creates a bare state with no question.
    final state = _assessmentEngine.begin(
      studentId: context.studentId,
      profile: context.profile,
      allQuestions: _allQuestions,
    );

    final firstQuestion = state.activeQuestion;
    final response = firstQuestion == null
        ? _tr(context,
            ar: 'سنبدأ التقييم الأكاديمي الآن. لا توجد أسئلة محملة حالياً — سيتم تحميل قاعدة المعرفة قريباً.',
            en: 'We will begin the assessment now. No questions are loaded yet — the knowledge base will be loaded soon.')
        : _tr(context,
            ar: 'رائع! لنبدأ تقييمك الأكاديمي.\n\n${_formatQuestion(firstQuestion, context)}',
            en: 'Great! Let\'s begin your academic assessment.\n\n${_formatQuestion(firstQuestion, context)}');

    final updatedMemory = context.memory
        .updateAssessmentState(state)
        .appendTurn(_turn(
          context: context,
          content: response,
          eventType: ConversationEventType.questionAsked,
          isEngine: true,
        ));

    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: context.phase.transitionTo(ConversationStage.assessment),
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionAsked),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Conversation Completion — Pending Need Resolution
  // ─────────────────────────────────────────────────────────────────────────

  /// Called when [ConversationPhase.pendingNeed] is non-null and the student
  /// sends another message.
  ///
  /// The student's new message may be:
  ///   (a) An answer to the pending need (e.g. follow-up to an example
  ///       validation) → clear the need, then repeat the question.
  ///   (b) Another question → address it and keep the need open.
  ///
  /// This handler NEVER advances the assessment.
  ControllerResult _resolvePendingNeed(conv.ConversationContext context) {
    final need = context.phase.pendingNeed!;
    final activeQuestion = context.activeQuestion;

    switch (need) {
      case ExampleValidationNeed(:final studentExample):
        // The student had asked "Does X count?" — now confirm it and
        // re-present the assessment question for their actual answer.
        final confirm = _tr(context,
            ar: 'نعم، "$studentExample" هو مثال جيد تماماً ويمكنك الإجابة بناءً عليه.',
            en: 'Yes, "$studentExample" is a perfectly valid example and you can base your answer on it.');
        final questionBlock = activeQuestion != null
            ? '\n\n${_formatQuestion(activeQuestion, context)}'
            : '';
        final updatedPhase = context.phase.withNeedResolved();
        final updatedMemory = _updateMemory(
          context: context,
          updatedState: context.memory.assessmentState,
          phase: updatedPhase,
        );
        return ControllerResult(
          response: '$confirm$questionBlock',
          updatedMemory: updatedMemory,
          updatedPhase: updatedPhase,
          updatedLanguage: context.language,
          updatedProfile: context.profile,
          event: _event(ConversationEventType.questionExplained),
          assessmentAdvanced: false,
          recommendationGenerated: false,
        );

      case FollowUpClarificationNeed(:final followUpQuestion):
        // The student had a follow-up after an explanation — answer it,
        // then re-present the question. Need is now resolved.
        final answer = _tr(context,
            ar: 'سؤال وجيه — "$followUpQuestion". '
                'يمكنك الإجابة بأي شكل يعكس وجهة نظرك الحقيقية، '
                'لا توجد إجابة خاطئة هنا.',
            en: 'Good question — "$followUpQuestion". '
                'You can answer in any way that reflects your genuine perspective, '
                'there is no wrong answer here.');
        final questionBlock = activeQuestion != null
            ? '\n\n${_formatQuestion(activeQuestion, context)}'
            : '';
        final updatedPhase = context.phase.withNeedResolved();
        final updatedMemory = _updateMemory(
          context: context,
          updatedState: context.memory.assessmentState,
          phase: updatedPhase,
        );
        return ControllerResult(
          response: '$answer$questionBlock',
          updatedMemory: updatedMemory,
          updatedPhase: updatedPhase,
          updatedLanguage: context.language,
          updatedProfile: context.profile,
          event: _event(ConversationEventType.questionExplained),
          assessmentAdvanced: false,
          recommendationGenerated: false,
        );
    }
  }

  Future<ControllerResult> _handleAcademicDiscussion(
    conv.ConversationContext context,
    RouteDecision routeDecision,
  ) async {
    // Use LLM for academic responses when available; fall back to template.
    final response = await _buildAcademicResponseLlm(context);

    // Return-to-assessment bridge message.
    final returnBridge = context.policy.autoReturnAfterDiscussion &&
            context.phase.stage.canReceiveAnswer &&
            context.activeQuestion != null
        ? '\n\n${_tr(context, ar: "لنعد إلى التقييم:", en: "Let us return to the assessment:")}\n${_formatQuestion(context.activeQuestion!, context)}'
        : '';

    final updatedPhase = context.phase
        .interrupt()
        .incrementDiscussionDepth();

    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );

    return ControllerResult(
      response: '$response$returnBridge',
      updatedMemory: updatedMemory,
      updatedPhase: routeDecision.willReturnToAssessment
          ? updatedPhase.resumeFromInterruption()
          : updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.academicDiscussion,
          intent: context.decision.detectedIntent.name),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  ControllerResult _handleRecommendationDiscussion(
      conv.ConversationContext context) {
    final report = context.memory.recommendationReport;
    if (report == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لم يتم إنشاء توصية بعد. سنكمل التقييم أولاً.',
            en: 'No recommendation has been generated yet. Let\'s complete the assessment first.'),
        eventType: ConversationEventType.recommendationDiscussed,
        assessmentAdvanced: false,
      );
    }

    final response = _buildRecommendationDiscussionResponse(
        context, report);

    final updatedPhase =
        context.phase.transitionTo(ConversationStage.postRecommendation);

    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );

    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.recommendationDiscussed),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  Future<ControllerResult> _handleClarification(conv.ConversationContext context) async {
    final activeQuestion = context.activeQuestion;
    if (activeQuestion == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لا يوجد سؤال نشط حالياً لشرحه.',
            en: 'There is no active question to explain right now.'),
        eventType: ConversationEventType.questionExplained,
        assessmentAdvanced: false,
      );
    }

    final recentHistory = context.memory.contextWindow(context.policy);
    final explanation = await _explanationService.generate(
      intent: QulIntent.clarification,
      question: activeQuestion,
      studentMessage: context.studentMessage,
      isArabic: context.isArabic,
      recentHistory: recentHistory,
      clarificationCount: context.phase.clarificationCount,
    );

    final repeat = context.policy.repeatQuestionAfterExplanation
        ? '\n\n${_formatQuestion(activeQuestion, context)}'
        : '';

    final updatedPhase = context.phase.addClarification();
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );

    return ControllerResult(
      response: '$explanation$repeat',
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionExplained),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  ControllerResult _handleGreeting(conv.ConversationContext context) {
    final response = _tr(context,
        ar: 'أهلاً وسهلاً! أنا مستشارك الأكاديمي الذكي. هنا لمساعدتك في اكتشاف أفضل التخصصات التي تناسب شخصيتك وقدراتك.',
        en: 'Welcome! I am your AI academic advisor. I\'m here to help you discover the best majors that match your personality and abilities.');

    return _simple(
      context: context,
      response: response,
      eventType: ConversationEventType.greeting,
      assessmentAdvanced: false,
    );
  }

  ControllerResult _handleHelp(conv.ConversationContext context) {
    final response = _tr(context,
        ar: 'يمكنني مساعدتك في:\n- الإجابة على أسئلة التقييم\n- الإجابة على أسئلتك الأكاديمية\n- شرح أي سؤال\n- تخطي سؤال\n- مناقشة التوصيات الأكاديمية',
        en: 'I can help you with:\n- Answering assessment questions\n- Answering your academic questions\n- Explaining any question\n- Skipping a question\n- Discussing academic recommendations');

    return _simple(
      context: context,
      response: response,
      eventType: ConversationEventType.engineResponse,
      assessmentAdvanced: false,
    );
  }

  ControllerResult _handleSkipQuestion(conv.ConversationContext context) {
    final state = context.memory.assessmentState;
    if (state == null || context.activeQuestion == null) {
      return _handleGreeting(context);
    }

    // Delegate entirely to AdaptiveAssessmentEngine.skip().
    // This is the ONLY component authorised to select the next question.
    // No inline question filter here — QuestionSelector handles it with full
    // phase/coverage/gap awareness.
    final skipResult = _assessmentEngine.skip(
      currentState: state,
      allQuestions: _allQuestions,
    );

    final updatedState = skipResult.updatedState;
    final nextQ = skipResult.nextQuestion;

    final response = nextQ != null
        ? '${_tr(context, ar: "تم تخطي السؤال.", en: "Question skipped.")}\n\n${_formatQuestion(nextQ, context)}'
        : _tr(context,
            ar: 'لا توجد أسئلة إضافية. سيتم تحليل نتائجك الآن.',
            en: 'No more questions. Your results will be analysed now.');

    final updatedMemory = _updateMemory(
      context: context,
      updatedState: updatedState,
      phase: context.phase,
    );

    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: context.phase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionSkipped),
      assessmentAdvanced: true,
      recommendationGenerated: false,
    );
  }

  ControllerResult _handleRestartAssessment(conv.ConversationContext context) {
    final freshProfile =
        StudentCognitiveProfile.initial(studentId: context.studentId);

    // Use _assessmentEngine.restart() — NOT _assessmentController.start().
    // restart() calls begin() internally, which runs QuestionSelector and
    // sets the first question immediately. start() alone leaves activeQuestion null.
    final existingState = context.memory.assessmentState ??
        _assessmentController.start(
          studentId: context.studentId,
          profile: freshProfile,
        );

    final newState = _assessmentEngine.restart(
      state: existingState,
      freshProfile: freshProfile,
      allQuestions: _allQuestions,
    );

    final firstQ = newState.activeQuestion;
    final response = _tr(context,
        ar: 'تم إعادة التقييم من البداية.\n\n${firstQ != null ? _formatQuestion(firstQ, context) : ""}',
        en: 'Assessment restarted from the beginning.\n\n${firstQ != null ? _formatQuestion(firstQ, context) : ""}');

    final updatedMemory = ConversationMemory.empty(context.sessionId)
        .updateAssessmentState(newState);
    final updatedPhase = ConversationPhase.initial()
        .transitionTo(ConversationStage.assessment);

    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: freshProfile,
      event: _event(ConversationEventType.assessmentRestarted),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  ControllerResult _handleGoodbye(conv.ConversationContext context) {
    final response = _tr(context,
        ar: 'شكراً لوقتك. أتمنى لك التوفيق في مسيرتك الأكاديمية!',
        en: 'Thank you for your time. Best of luck on your academic journey!');

    return ControllerResult(
      response: response,
      updatedMemory: context.memory,
      updatedPhase: context.phase.transitionTo(ConversationStage.closing),
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.goodbye),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  ControllerResult _handleUnknown(conv.ConversationContext context) {
    final response = _tr(context,
        ar: 'لم أفهم رسالتك تماماً. هل يمكنك توضيح ما تقصده؟',
        en: 'I didn\'t quite understand your message. Could you clarify what you mean?');

    final resumeBridge = context.activeQuestion != null &&
            context.phase.stage.canReceiveAnswer
        ? '\n\n${_formatQuestion(context.activeQuestion!, context)}'
        : '';

    return _simple(
      context: context,
      response: '$response$resumeBridge',
      eventType: ConversationEventType.unknown,
      assessmentAdvanced: false,
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Question Understanding Layer — Handlers
  // ─────────────────────────────────────────────────────────────────────────

  /// [SupportedIntent.askWordMeaning] — student asks what a term means.
  /// LLM explains the term in context. Assessment state: NEVER modified.
  Future<ControllerResult> _handleWordMeaning(conv.ConversationContext context) async {
    final activeQuestion = context.activeQuestion;
    if (activeQuestion == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لا يوجد سؤال نشط حالياً.',
            en: 'There is no active question right now.'),
        eventType: ConversationEventType.questionExplained,
        assessmentAdvanced: false,
      );
    }
    final recentHistory = context.memory.contextWindow(context.policy);
    final explanation = await _explanationService.generate(
      intent: QulIntent.wordMeaning,
      question: activeQuestion,
      studentMessage: context.studentMessage,
      isArabic: context.isArabic,
      recentHistory: recentHistory,
      clarificationCount: context.phase.clarificationCount,
    );
    // Always repeat the question after explaining a term — the student needs
    // the question in front of them to answer it.
    final updatedPhase = context.phase.addClarification();
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );
    return ControllerResult(
      response: '$explanation\n\n${_formatQuestion(activeQuestion, context)}',
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionExplained),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  /// [SupportedIntent.expressUncertainty] — student says they don't know.
  /// LLM simplifies + provides examples. After 2 clarifications, escalates to skip().
  /// Assessment state: only mutated via _assessmentEngine.skip() if escalating.
  Future<ControllerResult> _handleUncertainty(conv.ConversationContext context) async {
    final activeQuestion = context.activeQuestion;
    if (activeQuestion == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لا يوجد سؤال نشط حالياً.',
            en: 'There is no active question right now.'),
        eventType: ConversationEventType.questionExplained,
        assessmentAdvanced: false,
      );
    }

    const maxBeforeEscalation = 2;
    final clarificationsSoFar = context.phase.clarificationCount;

    if (clarificationsSoFar >= maxBeforeEscalation) {
      // Escalate: skip() is the ONLY mutation — assessment engine stays in control.
      final state = context.memory.assessmentState!;
      final skipResult = _assessmentEngine.skip(
        currentState: state,
        allQuestions: _allQuestions,
        preferredDomainIds: activeQuestion.targetDomainIds,
      );
      final updatedState = skipResult.updatedState;
      final nextQ = skipResult.nextQuestion;
      final intro = _tr(context,
          ar: 'لا بأس — لننتقل لسؤال مشابه:\n\n',
          en: 'No worries — let\'s try a related question:\n\n');
      final response = nextQ != null
          ? '$intro${_formatQuestion(nextQ, context)}'
          : _tr(context,
              ar: 'لا مشكلة — لقد أجبت على ما يكفي. سيتم إعداد توصياتك الآن.',
              en: 'No problem — you\'ve answered enough. Preparing your recommendations now.');
      final updatedPhase =
          context.phase.addClarification().copyWith(clarificationCount: 0);
      final updatedMemory = _updateMemory(
        context: context,
        updatedState: updatedState,
        phase: updatedPhase,
      );
      return ControllerResult(
        response: response,
        updatedMemory: updatedMemory,
        updatedPhase: updatedPhase,
        updatedLanguage: context.language,
        updatedProfile: context.profile,
        event: _event(ConversationEventType.questionSkipped),
        assessmentAdvanced: true,
        recommendationGenerated: false,
      );
    }

    // First or second attempt: LLM simplifies the question.
    final recentHistory = context.memory.contextWindow(context.policy);
    final simplified = await _explanationService.generate(
      intent: QulIntent.uncertainty,
      question: activeQuestion,
      studentMessage: context.studentMessage,
      isArabic: context.isArabic,
      recentHistory: recentHistory,
      clarificationCount: clarificationsSoFar,
    );
    final updatedPhase = context.phase.addClarification();
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );
    return ControllerResult(
      response: simplified,
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionExplained),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  /// [SupportedIntent.askWhyThisQuestion] — student asks the purpose.
  /// LLM explains using question type + domain. Assessment state: NEVER modified.
  Future<ControllerResult> _handleWhyThisQuestion(conv.ConversationContext context) async {
    final activeQuestion = context.activeQuestion;
    if (activeQuestion == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لا يوجد سؤال نشط حالياً.',
            en: 'There is no active question right now.'),
        eventType: ConversationEventType.questionExplained,
        assessmentAdvanced: false,
      );
    }
    final recentHistory = context.memory.contextWindow(context.policy);
    final purpose = await _explanationService.generate(
      intent: QulIntent.whyThisQuestion,
      question: activeQuestion,
      studentMessage: context.studentMessage,
      isArabic: context.isArabic,
      recentHistory: recentHistory,
      clarificationCount: context.phase.clarificationCount,
    );
    final updatedPhase = context.phase.addClarification();
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );
    return ControllerResult(
      response: '$purpose\n\n${_formatQuestion(activeQuestion, context)}',
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionExplained),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  /// [SupportedIntent.requestAlternativeQuestion] — student wants a different question.
  /// Delegates ONLY to _assessmentEngine.skip() with domain preference.
  /// Assessment state: mutated exclusively by the engine.
  ControllerResult _handleAlternativeQuestion(conv.ConversationContext context) {
    final activeQuestion = context.activeQuestion;
    final state = context.memory.assessmentState;
    if (activeQuestion == null || state == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لا يوجد سؤال نشط يمكن تغييره.',
            en: 'There is no active question to replace.'),
        eventType: ConversationEventType.questionSkipped,
        assessmentAdvanced: false,
      );
    }
    final skipResult = _assessmentEngine.skip(
      currentState: state,
      allQuestions: _allQuestions,
      preferredDomainIds: activeQuestion.targetDomainIds,
    );
    final updatedState = skipResult.updatedState;
    final nextQ = skipResult.nextQuestion;
    final intro = _tr(context,
        ar: 'بالتأكيد، إليك سؤال آخر:\n\n',
        en: 'Of course, here is another question:\n\n');
    final response = nextQ != null
        ? '$intro${_formatQuestion(nextQ, context)}'
        : _tr(context,
            ar: 'لا توجد أسئلة إضافية متاحة. سيتم إعداد توصياتك الآن.',
            en: 'No more questions available. Preparing your recommendations now.');
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: updatedState,
      phase: context.phase,
    );
    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: context.phase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionSkipped),
      assessmentAdvanced: true,
      recommendationGenerated: false,
    );
  }

  /// [SupportedIntent.requestExamples] — student asks for examples.
  /// LLM generates domain-specific examples. Assessment state: NEVER modified.
  ///
  /// Special case — Example Validation:
  /// If the student's message is a concrete "Does X count?" question
  /// (e.g. "هل التنمر يُعتبر قيادة؟", "يعني زواجي يحسب؟"), this handler
  /// answers that specific question directly and sets a [ExampleValidationNeed]
  /// so the assessment does NOT advance until the student gives their real answer.
  Future<ControllerResult> _handleQuestionExamples(conv.ConversationContext context) async {
    final activeQuestion = context.activeQuestion;
    if (activeQuestion == null) {
      return _simple(
        context: context,
        response: _tr(context,
            ar: 'لا يوجد سؤال نشط حالياً.',
            en: 'There is no active question right now.'),
        eventType: ConversationEventType.questionExplained,
        assessmentAdvanced: false,
      );
    }

    // ── Detect example-validation pattern ──────────────────────────────────
    // Patterns: "هل X يُعدّ/يحسب/يعتبر...؟", "يعني X يصلح؟", "Does X count?",
    // "Is X an example of...?"
    final exampleCandidate = _extractExampleValidationCandidate(context.studentMessage);
    if (exampleCandidate != null) {
      // Answer the validation question directly without advancing assessment.
      final validationResponse = _tr(context,
          ar: 'نعم، "$exampleCandidate" هو مثال ممتاز تماماً. '
              'يمكنك ذكره في إجابتك بشكل مباشر.\n\n'
              '${_formatQuestion(activeQuestion, context)}',
          en: 'Yes, "$exampleCandidate" is a perfectly valid example. '
              'You can mention it directly in your answer.\n\n'
              '${_formatQuestion(activeQuestion, context)}');
      // Set a pending need so the next message is treated as their answer
      // (not another clarification request).
      final updatedPhase = context.phase
          .addClarification()
          .withPendingNeed(ExampleValidationNeed(exampleCandidate));
      final updatedMemory = _updateMemory(
        context: context,
        updatedState: context.memory.assessmentState,
        phase: updatedPhase,
      );
      return ControllerResult(
        response: validationResponse,
        updatedMemory: updatedMemory,
        updatedPhase: updatedPhase,
        updatedLanguage: context.language,
        updatedProfile: context.profile,
        event: _event(ConversationEventType.questionExplained),
        assessmentAdvanced: false,
        recommendationGenerated: false,
      );
    }

    // ── Standard examples request ───────────────────────────────────────────
    final recentHistory = context.memory.contextWindow(context.policy);
    final examples = await _explanationService.generate(
      intent: QulIntent.examples,
      question: activeQuestion,
      studentMessage: context.studentMessage,
      isArabic: context.isArabic,
      recentHistory: recentHistory,
      clarificationCount: context.phase.clarificationCount,
    );
    final updatedPhase = context.phase.addClarification();
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: updatedPhase,
    );
    return ControllerResult(
      response: '$examples\n\n${_formatQuestion(activeQuestion, context)}',
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(ConversationEventType.questionExplained),
      assessmentAdvanced: false,
      recommendationGenerated: false,
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Recommendation generation
  // ─────────────────────────────────────────────────────────────────────────

  ControllerResult _generateRecommendation({
    required conv.ConversationContext context,
    required AssessmentState updatedState,
    required StudentCognitiveProfile updatedProfile,
    required dynamic stats,
  }) {
    final ranking = _matchingEngine.match(
      profile: updatedProfile,
      allMajors: _allMajors,
    );

    final report = _recommendationEngine.produce(
      studentId: context.studentId,
      profile: updatedProfile,
      ranking: ranking,
      stats: stats,
    );

    final explainableReport = _explainableEngine.explain(
      report: report,
      profile: updatedProfile,
      ranking: ranking,
    );

    final response = _formatRecommendationResponse(
        report, explainableReport, context);

    final updatedPhase =
        context.phase.transitionTo(ConversationStage.recommendation);

    final updatedMemory = context.memory
        .updateAssessmentState(updatedState)
        .storeRecommendation(report)
        .appendTurn(_turn(
          context: context,
          content: response,
          eventType: ConversationEventType.recommendationGenerated,
          isEngine: true,
        ));

    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: updatedPhase,
      updatedLanguage: context.language,
      updatedProfile: updatedProfile,
      event: _event(ConversationEventType.recommendationGenerated),
      assessmentAdvanced: true,
      recommendationGenerated: true,
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Response builders
  // ─────────────────────────────────────────────────────────────────────────

  /// Formats the active assessment question for display to the student.
  ///
  /// Always shows the question text. Appends:
  ///   - The hint line when present (e.g. "اختر ما ينطبق عليك").
  ///   - The numbered answer options when defined (multiple-choice / multi-select).
  ///
  /// This makes the repeated question block self-contained so the student
  /// never has to scroll back to see the options.
  String _formatQuestion(Question q, conv.ConversationContext ctx) {
    final buf = StringBuffer(q.text);

    // Append hint when provided.
    if (q.hint != null && q.hint!.trim().isNotEmpty) {
      buf.write('\n${q.hint!.trim()}');
    }

    // Append numbered options for structured question types.
    if (q.options.isNotEmpty) {
      buf.write('\n');
      for (var i = 0; i < q.options.length; i++) {
        buf.write('\n${i + 1}. ${q.options[i].label}');
      }
    }

    return buf.toString();
  }




  Future<String> _buildAcademicResponseLlm(
    conv.ConversationContext ctx,
  ) async {
    // Build a rich prompt for the academic discussion — the LLM reasons about
    // what the student is asking and provides a helpful, non-assessment response.
    if (_explanationService.isLlmEnabled) {
      try {
        final recentHistory = ctx.memory.contextWindow(ctx.policy);
        final activeQ = ctx.activeQuestion;
        final buf = StringBuffer();

        if (ctx.isArabic) {
          buf.writeln('=== سياق المحادثة الأكاديمية ===');
          buf.writeln('الطالب في منتصف تقييم أكاديمي.');
          if (activeQ != null) {
            buf.writeln('سؤال التقييم الحالي: "${activeQ.text}"');
          }
          buf.writeln();
          if (recentHistory.isNotEmpty) {
            buf.writeln('=== آخر رسائل المحادثة ===');
            for (final turn in recentHistory.take(6)) {
              final role = turn.isStudent ? 'الطالب' : 'المستشار';
              buf.writeln('$role: ${turn.content.trim()}');
            }
            buf.writeln();
          }
          buf.writeln('=== سؤال الطالب ===');
          buf.writeln('"${ctx.studentMessage}"');
          buf.writeln();
          buf.writeln('=== مهمتك ===');
          buf.writeln(
            'أجب على سؤال الطالب الأكاديمي بشكل طبيعي ومفيد.\n'
            'أنت مستشار أكاديمي — أجب بصدق وبشكل مناسب لمستوى طالب جامعي.\n'
            'لا تقترح تخصصاً أو توصية — هذا القرار للنظام.\n'
            'لا تُجب عن سؤال التقييم الحالي نيابةً عن الطالب.\n'
            'أجب باللغة التي استخدمها الطالب.',
          );
        } else {
          buf.writeln('=== ACADEMIC CONVERSATION CONTEXT ===');
          buf.writeln('The student is in the middle of an academic assessment.');
          if (activeQ != null) {
            buf.writeln('Current assessment question: "${activeQ.text}"');
          }
          buf.writeln();
          if (recentHistory.isNotEmpty) {
            buf.writeln('=== RECENT CONVERSATION ===');
            for (final turn in recentHistory.take(6)) {
              final role = turn.isStudent ? 'Student' : 'Advisor';
              buf.writeln('$role: ${turn.content.trim()}');
            }
            buf.writeln();
          }
          buf.writeln("=== STUDENT'S QUESTION ===");
          buf.writeln('"${ctx.studentMessage}"');
          buf.writeln();
          buf.writeln('=== YOUR TASK ===');
          buf.writeln(
            'Answer the student\'s academic question naturally and helpfully.\n'
            'You are an academic advisor — respond honestly and appropriately for a university-level student.\n'
            'Do not suggest a major or recommendation — that is the system\'s decision.\n'
            'Do not answer the current assessment question on the student\'s behalf.\n'
            'Respond in the language the student used.',
          );
        }

        final llmResponse = await _explanationService.generateAcademicResponse(
          prompt: buf.toString(),
          isArabic: ctx.isArabic,
        );
        if (llmResponse.trim().isNotEmpty) {
          return llmResponse;
        }
      } catch (_) {
        // Fall through to template fallback below.
      }
    }

    // Template fallback — used when LLM is disabled or fails.
    return _tr(
      ctx,
      ar: '${ctx.studentMessage}\n\nهذا سؤال وجيه. '  
          'يمكنني مساعدتك بما لدي من معلومات أكاديمية عامة، '
          'وإذا احتجت تفاصيل أعمق فالأفضل الرجوع لأستاذ متخصص.',
      en: '${ctx.studentMessage}\n\nThat\'s a fair question. '
          'I can help with general academic information I have, '
          'but for deeper details you\'d be best served by a specialist in that field.',
    );
  }

  String _buildRecommendationDiscussionResponse(
    conv.ConversationContext ctx,
    RecommendationReport report,
  ) {
    final topPick = report.topPick;
    if (topPick == null) {
      return _tr(ctx,
          ar: 'لم يتم التوصية بأي تخصص بعد. يحتاج التقييم إلى مزيد من الأسئلة.',
          en: 'No major has been recommended yet. The assessment needs more questions.');
    }

    final msg = ctx.studentMessage.toLowerCase();
    if (msg.contains('لماذا') ||
        msg.contains('why') ||
        msg.contains('how come')) {
      final strengthLabels = topPick.topStrengths
          .take(3)
          .map((k) => _friendlyDimensionLabel(k, ctx.isArabic))
          .join(ctx.isArabic ? '، ' : ', ');
      return _tr(ctx,
          ar: 'تم اختيار "${topPick.majorName}" لأنه يتناسب مع قدراتك الأكاديمية بنسبة ${topPick.similarityScore}%. نقاط قوتك في: $strengthLabels.',
          en: '"${topPick.majorName}" was selected because it matches your academic abilities by ${topPick.similarityScore}%. Your key strengths: $strengthLabels.');
    }

    if (msg.contains('وظيفة') ||
        msg.contains('مهنة') ||
        msg.contains('job') ||
        msg.contains('career')) {
      return _tr(ctx,
          ar: 'تخصص "${topPick.majorName}" يفتح أمامك فرص مهنية عديدة. لمعرفة التفاصيل، تحدث مع المرشد الأكاديمي في جامعتك.',
          en: 'The "${topPick.majorName}" major opens many career opportunities. For details, speak with your university\'s academic advisor.');
    }

    if (msg.contains('صعب') ||
        msg.contains('صعوبة') ||
        msg.contains('difficult') ||
        msg.contains('hard')) {
      return _tr(ctx,
          ar: 'كل تخصص له تحدياته، لكن مع تطابق قدراتك مع "${topPick.majorName}" بنسبة ${topPick.similarityScore}%، ستكون قادراً على التفوق.',
          en: 'Every major has its challenges, but with your ${topPick.similarityScore}% match with "${topPick.majorName}", you will be able to excel.');
    }

    // Generic discussion response.
    final reasons = topPick.reasons.take(2).map((r) => r.title).join(', ');
    return _tr(ctx,
        ar: 'توصيتك هي "${topPick.majorName}" بنسبة تطابق ${topPick.similarityScore}%. الأسباب الرئيسية: $reasons. هل لديك سؤال محدد؟',
        en: 'Your recommendation is "${topPick.majorName}" with a ${topPick.similarityScore}% match score. Key reasons: $reasons. Do you have a specific question?');
  }

  String _formatRecommendationResponse(
    RecommendationReport report,
    ExplainableReport explainableReport,
    conv.ConversationContext ctx,
  ) {
    if (!report.hasRecommendations) {
      return _tr(ctx,
          ar: 'شكراً على إجاباتك. نحتاج إلى مزيد من المعلومات لتقديم توصية دقيقة. ${report.statusMessage}',
          en: 'Thank you for your answers. We need more information to make an accurate recommendation. ${report.statusMessage}');
    }

    final top = report.topPick!;
    final narrative = explainableReport.decisionExplanation.narrative;
    final suggestions = explainableReport.improvementSuggestions
        .take(2)
        .map((s) => '• ${s.title}')
        .join('\n');

    return _tr(ctx,
        ar: '🎓 بناءً على تقييمك الأكاديمي:\n\n'
            'التخصص الأنسب لك هو: ${top.majorName}\n'
            'نسبة التطابق: ${top.similarityScore}%\n\n'
            '$narrative\n\n'
            '📋 توصيات للتطوير:\n$suggestions\n\n'
            'هل تريد معرفة المزيد عن هذا التخصص؟',
        en: '🎓 Based on your academic assessment:\n\n'
            'Your best match major is: ${top.majorName}\n'
            'Match score: ${top.similarityScore}%\n\n'
            '$narrative\n\n'
            '📋 Development recommendations:\n$suggestions\n\n'
            'Would you like to know more about this major?');
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Helpers
  // ─────────────────────────────────────────────────────────────────────────

  String _tr(
    conv.ConversationContext ctx, {
    required String ar,
    required String en,
  }) => ctx.isArabic ? ar : en;

  // ─────────────────────────────────────────────────────────────────────────
  // Example Validation Detector
  // ─────────────────────────────────────────────────────────────────────────

  /// Detects whether the student's message is asking if a specific example
  /// is valid as an answer ("هل التنمر يُعتبر قيادة؟", "Does bullying count?").
  ///
  /// Returns the extracted candidate example string, or null if not detected.
  String? _extractExampleValidationCandidate(String message) {
    final msg = message.trim();

    // Arabic validation patterns
    final arPatterns = [
      RegExp(r'هل\s+(.+?)\s+(يُعدّ|يُعد|يعتبر|يحسب|يصلح|يُصنّف|يندرج)', unicode: true),
      RegExp(r'(.+?)\s+(تُعدّ|تعتبر|تحسب|تصلح)\s+(قيادة|إبداعاً|بحثاً|تواصلاً|مثالاً)', unicode: true),
      RegExp(r'يعني\s+(.+?)\s+(يصلح|يحسب|تحسب|يُعدّ)؟?$', unicode: true),
      RegExp(r'مثل\s+(.+?)\s+(يصلح|يحسب|يُعدّ)\s+(هنا|للإجابة)', unicode: true),
    ];

    // English validation patterns
    final enPatterns = [
      RegExp(r'(?:does|do|would)\s+(.+?)\s+(?:count|qualify|work)\b', caseSensitive: false),
      RegExp(r'(?:is|are)\s+(.+?)\s+(?:an?|considered?|valid)\s+(?:example|answer)', caseSensitive: false),
      RegExp(r'(?:can I|could I)\s+(?:use|say|mention)\s+(.+?)\??$', caseSensitive: false),
    ];

    for (final pattern in [...arPatterns, ...enPatterns]) {
      final match = pattern.firstMatch(msg);
      if (match != null) {
        final candidate = match.group(1)?.trim();
        if (candidate != null && candidate.length >= 2) {
          return candidate;
        }
      }
    }
    return null;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Dimension Label Helper
  // ─────────────────────────────────────────────────────────────────────────

  /// Converts an internal DimensionKey (e.g. "problem_solving") to a
  /// natural-language label suitable for display to the student.
  ///
  /// Never exposes raw underscore-separated key strings.
  static const _arDimLabels = <String, String>{
    'logic':                    'التفكير المنطقي',
    'mathematics':              'الرياضيات',
    'creativity':               'الإبداع',
    'research':                 'البحث العلمي',
    'critical_thinking':        'التفكير النقدي',
    'problem_solving':          'حل المشكلات',
    'teamwork':                 'العمل الجماعي',
    'leadership':               'القيادة',
    'communication':            'التواصل والتعبير',
    'empathy':                  'التواصل الإنساني',
    'business':                 'الأعمال والإدارة',
    'technology':               'التقنية والحاسب',
    'science':                  'العلوم التجريبية',
    'language':                 'اللغة والأدب',
    'art':                      'الفن والتصميم',
    'medicine':                 'الطب والصحة',
    'law':                      'القانون',
    'self_learning':            'التعلم الذاتي',
    'stress_preference':        'تحمّل ضغط العمل',
    'decision_style':           'أسلوب اتخاذ القرار',
    'technology_affinity':      'الانجذاب للتقنية',
    'practical_vs_theoretical': 'التطبيق مقابل النظرية',
    'academic_performance':     'الأداء الأكاديمي',
    'ambiguity_tolerance':      'تحمّل الغموض',
  };

  static const _enDimLabels = <String, String>{
    'logic':                    'Logical Reasoning',
    'mathematics':              'Mathematics',
    'creativity':               'Creativity',
    'research':                 'Research',
    'critical_thinking':        'Critical Thinking',
    'problem_solving':          'Problem Solving',
    'teamwork':                 'Teamwork',
    'leadership':               'Leadership',
    'communication':            'Communication',
    'empathy':                  'Empathy & Human Connection',
    'business':                 'Business & Management',
    'technology':               'Technology & Computing',
    'science':                  'Science',
    'language':                 'Language & Literature',
    'art':                      'Art & Design',
    'medicine':                 'Medicine & Health',
    'law':                      'Law',
    'self_learning':            'Self-Learning',
    'stress_preference':        'Stress Tolerance',
    'decision_style':           'Decision Style',
    'technology_affinity':      'Technology Affinity',
    'practical_vs_theoretical': 'Practical vs Theoretical',
    'academic_performance':     'Academic Performance',
    'ambiguity_tolerance':      'Ambiguity Tolerance',
  };

  String _friendlyDimensionLabel(String key, bool isArabic) {
    final labels = isArabic ? _arDimLabels : _enDimLabels;
    // Return mapped label, or a safe generic fallback — never the raw key.
    return labels[key] ?? (isArabic ? 'المجال الأكاديمي' : 'academic ability');
  }

  ControllerResult _simple({
    required conv.ConversationContext context,
    required String response,
    required ConversationEventType eventType,
    required bool assessmentAdvanced,
  }) {
    final updatedMemory = _updateMemory(
      context: context,
      updatedState: context.memory.assessmentState,
      phase: context.phase,
    );
    return ControllerResult(
      response: response,
      updatedMemory: updatedMemory,
      updatedPhase: context.phase,
      updatedLanguage: context.language,
      updatedProfile: context.profile,
      event: _event(eventType),
      assessmentAdvanced: assessmentAdvanced,
      recommendationGenerated: false,
    );
  }

  ConversationMemory _updateMemory({
    required conv.ConversationContext context,
    required AssessmentState? updatedState,
    required ConversationPhase phase,
  }) {
    var memory = context.memory;
    if (updatedState != null) {
      memory = memory.updateAssessmentState(updatedState);
    }

    // Auto-summarise if due.
    if (memory.shouldSummarise(context.policy)) {
      final turns = memory.turnsSinceLastSummary();
      if (turns.isNotEmpty) {
        final summary = ConversationSummary.generate(
          summaryId: _uuid.v4(),
          sessionId: context.sessionId,
          turns: turns,
          phase: phase,
          profile: context.profile,
        );
        memory = memory.addSummary(summary);
      }
    }

    return memory;
  }

  ConversationTurnRecord _turn({
    required conv.ConversationContext context,
    required String content,
    required ConversationEventType eventType,
    required bool isEngine,
  }) => ConversationTurnRecord(
    turnId: _uuid.v4(),
    role: isEngine ? MessageRole.engine : MessageRole.student,
    content: content,
    wasAssessmentTurn: context.phase.stage.canReceiveAnswer,
    wasInterruption: false,
    wasClarification:
        eventType == ConversationEventType.questionExplained,
    timestamp: DateTime.now().toUtc(),
  );

  ConversationEvent _event(
    ConversationEventType type, {
    String? intent,
  }) => ConversationEvent(
    eventId: _uuid.v4(),
    type: type,
    payload: intent,
    occurredAt: DateTime.now().toUtc(),
  );

  dec.ConversationContext _buildDecisionContext(
    conv.ConversationContext context,
    AssessmentState state,
  ) => dec.ConversationContext(
    studentId: context.studentId,
    currentPhase: state.phase,
    currentGoal: AssessmentGoal(
      id: 'default',
      type: AssessmentGoalType.majorSelection,
      focusDomainIds: const [],
      createdAt: DateTime.now().toUtc(),
    ),
    activeQuestion: state.activeQuestion,
    cognitiveProfile: context.profile,
    recentHistory: context.memory
        .contextWindow(context.policy)
        .map((t) => dec.ConversationTurn(
              role: t.role,
              content: t.content,
              timestamp: t.timestamp,
            ))
        .toList(),
    lastEngineMessage: context.memory.history.lastEngineMessage,
    lastStudentMessage: context.memory.history.lastStudentMessage,
    answeredQuestionIds: state.askedQuestionIds,
    skippedQuestionIds: state.skippedQuestionIds,
    unevidencedDimensionKeys: const [],
    consecutiveOffTopicCount: context.phase.interruptionCount,
    discussionCount: context.phase.discussionDepth,
    clarificationCount: context.phase.clarificationCount,
    conversationStage: context.phase.stage,
    activeLanguage: context.language.active,
    createdAt: DateTime.now().toUtc(),
  );

  // ─── Question History Reconstruction ─────────────────────────────────────

  /// Rebuilds a [QuestionHistory] from the ids stored in [AssessmentState].
  ///
  /// This gives [QuestionSelector] full visibility into ALL previously asked
  /// questions — not just the one answered in the current turn.
  ///
  /// Domain keys are resolved from [_allQuestions] when possible. Questions
  /// that no longer exist in the pool are recorded with empty domain keys;
  /// that is safe because they are already excluded by the asked-ids filter.
  QuestionHistory _buildQuestionHistory(AssessmentState state) {
    final questionIndex = {for (final q in _allQuestions) q.id: q};
    final now = DateTime.now().toUtc();

    final records = <QuestionRecord>[];

    // All asked (answered + skipped) questions go in first.
    for (final id in state.askedQuestionIds) {
      final q = questionIndex[id];
      final isSkipped = state.skippedQuestionIds.contains(id);
      records.add(QuestionRecord(
        questionId: id,
        outcome:
            isSkipped ? QuestionOutcome.skipped : QuestionOutcome.answered,
        askedAt: now,
        domainKeys: q?.targetDomainIds ?? const [],
      ));
    }

    return QuestionHistory(records: records);
  }
}

