/// SAIE — ProfileStatistics
///
/// Computed aggregate statistics over the student's cognitive profile.
/// Generated on demand — never stored permanently.
library;

import 'package:equatable/equatable.dart';
import 'package:stustep/features/saie/profile/cognitive_dimension.dart';

// ─────────────────────────────────────────────────────────────────────────────
// DimensionStat
// ─────────────────────────────────────────────────────────────────────────────

/// Summarizes a single dimension for reporting.
final class DimensionStat extends Equatable {
  final String key;
  final String label;
  final double score;
  final double confidence;
  final int evidenceCount;
  final DimensionTrend trend;

  const DimensionStat({
    required this.key,
    required this.label,
    required this.score,
    required this.confidence,
    required this.evidenceCount,
    required this.trend,
  });

  factory DimensionStat.fromDimension(CognitiveDimension d) => DimensionStat(
    key: d.key,
    label: d.label,
    score: d.score,
    confidence: d.confidence,
    evidenceCount: d.evidenceCount,
    trend: d.trend,
  );

  factory DimensionStat.fromJson(Map<String, dynamic> json) => DimensionStat(
    key: json['key'] as String,
    label: json['label'] as String,
    score: (json['score'] as num).toDouble(),
    confidence: (json['confidence'] as num).toDouble(),
    evidenceCount: json['evidence_count'] as int,
    trend: DimensionTrend.values.byName(json['trend'] as String),
  );

  Map<String, dynamic> toJson() => {
    'key': key,
    'label': label,
    'score': score,
    'confidence': confidence,
    'evidence_count': evidenceCount,
    'trend': trend.name,
  };

  @override
  List<Object?> get props => [key, score, confidence];
}

// ─────────────────────────────────────────────────────────────────────────────
// ProfileStatistics
// ─────────────────────────────────────────────────────────────────────────────

/// Computed statistics over the entire student cognitive profile.
///
/// Generated by calling [StudentCognitiveProfile.computeStatistics()].
/// This object is immutable and should be recomputed after each update.
final class ProfileStatistics extends Equatable {
  /// Total number of assessment questions answered.
  final int totalQuestionsAnswered;

  /// Total number of evidence records collected.
  final int totalEvidenceCount;

  /// Total number of session turns (messages) processed.
  final int totalMessageCount;

  /// Overall profile confidence — mean confidence across all dimensions.
  final double overallConfidence;

  /// Fraction of tracked dimensions that have at least 1 evidence signal.
  /// Value in [0.0, 1.0].
  final double coverageRatio;

  /// Fraction of dimensions where confidence ≥ 0.6 AND score is consistent.
  /// Value in [0.0, 1.0].
  final double consistencyRatio;

  /// The top N strongest dimensions, sorted descending by score.
  final List<DimensionStat> strongestDimensions;

  /// The top N weakest dimensions (lowest score, with evidence), sorted ascending.
  final List<DimensionStat> weakestDimensions;

  /// The top N rising dimensions (positive trend).
  final List<DimensionStat> risingDimensions;

  /// The N dimensions with the lowest confidence.
  final List<DimensionStat> leastConfidentDimensions;

  /// UTC timestamp when these statistics were computed.
  final DateTime computedAt;

  const ProfileStatistics({
    required this.totalQuestionsAnswered,
    required this.totalEvidenceCount,
    required this.totalMessageCount,
    required this.overallConfidence,
    required this.coverageRatio,
    required this.consistencyRatio,
    required this.strongestDimensions,
    required this.weakestDimensions,
    required this.risingDimensions,
    required this.leastConfidentDimensions,
    required this.computedAt,
  });

  factory ProfileStatistics.empty() => ProfileStatistics(
    totalQuestionsAnswered: 0,
    totalEvidenceCount: 0,
    totalMessageCount: 0,
    overallConfidence: 0.0,
    coverageRatio: 0.0,
    consistencyRatio: 0.0,
    strongestDimensions: const [],
    weakestDimensions: const [],
    risingDimensions: const [],
    leastConfidentDimensions: const [],
    computedAt: DateTime.now().toUtc(),
  );

  factory ProfileStatistics.fromJson(Map<String, dynamic> json) =>
      ProfileStatistics(
        totalQuestionsAnswered: json['total_questions_answered'] as int,
        totalEvidenceCount: json['total_evidence_count'] as int,
        totalMessageCount: json['total_message_count'] as int,
        overallConfidence: (json['overall_confidence'] as num).toDouble(),
        coverageRatio: (json['coverage_ratio'] as num).toDouble(),
        consistencyRatio: (json['consistency_ratio'] as num).toDouble(),
        strongestDimensions: (json['strongest_dimensions'] as List<dynamic>)
            .map((e) => DimensionStat.fromJson(e as Map<String, dynamic>))
            .toList(),
        weakestDimensions: (json['weakest_dimensions'] as List<dynamic>)
            .map((e) => DimensionStat.fromJson(e as Map<String, dynamic>))
            .toList(),
        risingDimensions: (json['rising_dimensions'] as List<dynamic>)
            .map((e) => DimensionStat.fromJson(e as Map<String, dynamic>))
            .toList(),
        leastConfidentDimensions:
            (json['least_confident_dimensions'] as List<dynamic>)
                .map((e) => DimensionStat.fromJson(e as Map<String, dynamic>))
                .toList(),
        computedAt: DateTime.parse(json['computed_at'] as String),
      );

  Map<String, dynamic> toJson() => {
    'total_questions_answered': totalQuestionsAnswered,
    'total_evidence_count': totalEvidenceCount,
    'total_message_count': totalMessageCount,
    'overall_confidence': overallConfidence,
    'coverage_ratio': coverageRatio,
    'consistency_ratio': consistencyRatio,
    'strongest_dimensions': strongestDimensions.map((d) => d.toJson()).toList(),
    'weakest_dimensions': weakestDimensions.map((d) => d.toJson()).toList(),
    'rising_dimensions': risingDimensions.map((d) => d.toJson()).toList(),
    'least_confident_dimensions':
        leastConfidentDimensions.map((d) => d.toJson()).toList(),
    'computed_at': computedAt.toIso8601String(),
  };

  ProfileStatistics copyWith({
    int? totalQuestionsAnswered,
    int? totalEvidenceCount,
    int? totalMessageCount,
    double? overallConfidence,
    double? coverageRatio,
    double? consistencyRatio,
    List<DimensionStat>? strongestDimensions,
    List<DimensionStat>? weakestDimensions,
    List<DimensionStat>? risingDimensions,
    List<DimensionStat>? leastConfidentDimensions,
    DateTime? computedAt,
  }) => ProfileStatistics(
    totalQuestionsAnswered:
        totalQuestionsAnswered ?? this.totalQuestionsAnswered,
    totalEvidenceCount: totalEvidenceCount ?? this.totalEvidenceCount,
    totalMessageCount: totalMessageCount ?? this.totalMessageCount,
    overallConfidence: overallConfidence ?? this.overallConfidence,
    coverageRatio: coverageRatio ?? this.coverageRatio,
    consistencyRatio: consistencyRatio ?? this.consistencyRatio,
    strongestDimensions: strongestDimensions ?? this.strongestDimensions,
    weakestDimensions: weakestDimensions ?? this.weakestDimensions,
    risingDimensions: risingDimensions ?? this.risingDimensions,
    leastConfidentDimensions:
        leastConfidentDimensions ?? this.leastConfidentDimensions,
    computedAt: computedAt ?? this.computedAt,
  );

  /// Returns `true` if the profile has enough data for reliable recommendations.
  bool get isActionable =>
      totalEvidenceCount >= 5 && overallConfidence >= 0.40;

  @override
  List<Object?> get props => [
    totalEvidenceCount,
    overallConfidence,
    coverageRatio,
    computedAt,
  ];

  @override
  String toString() =>
      'ProfileStatistics(evidence: $totalEvidenceCount, '
      'confidence: ${overallConfidence.toStringAsFixed(2)}, '
      'coverage: ${(coverageRatio * 100).toStringAsFixed(0)}%)';
}
