// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrWrVmpE2odhHON3TC9CovgewzpF3nXys',
    appId: '1:611121520187:web:29098cb4172942f633c61e',
    messagingSenderId: '611121520187',
    projectId: 'stustep-app-99',
    authDomain: 'stustep-app-99.firebaseapp.com',
    storageBucket: 'stustep-app-99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8wPV5UQ_JA75f5GMKjJecrF-8b5QFq88',
    appId: '1:611121520187:android:2e7ba4a0b1490d0133c61e',
    messagingSenderId: '611121520187',
    projectId: 'stustep-app-99',
    storageBucket: 'stustep-app-99.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbyQSIjAUGcduUaBQ5c8pL13uBvUk2vaY',
    appId: '1:611121520187:ios:a6cdaa2292216e8b33c61e',
    messagingSenderId: '611121520187',
    projectId: 'stustep-app-99',
    storageBucket: 'stustep-app-99.firebasestorage.app',
    androidClientId: '611121520187-5784en371onui36466vcch9mhb1ast09.apps.googleusercontent.com',
    iosClientId: '611121520187-02kgpu68oq9tshgjn9v4svuff2r674vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.stustep',
  );
}
