// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-dCwcS4V2cRToHeRwxF8VyOj2Kf7SOpo',
    appId: '1:165136018294:web:453efc30560fd4b8fc6857',
    messagingSenderId: '165136018294',
    projectId: 'stustep-4c1ea',
    authDomain: 'stustep-4c1ea.firebaseapp.com',
    storageBucket: 'stustep-4c1ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9HImzJaeujqnsvRUrKgtDljWrCg6rd0',
    appId: '1:165136018294:android:1890c30e102959dbfc6857',
    messagingSenderId: '165136018294',
    projectId: 'stustep-4c1ea',
    storageBucket: 'stustep-4c1ea.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8DIQjxYZGHAmaMZdwn0RQToxm3C5TpU',
    appId: '1:165136018294:ios:223a27f1dc62f06cfc6857',
    messagingSenderId: '165136018294',
    projectId: 'stustep-4c1ea',
    storageBucket: 'stustep-4c1ea.firebasestorage.app',
    androidClientId: '165136018294-3h92596n21j0v0kqh91hp5jjgm1q4drp.apps.googleusercontent.com',
    iosClientId: '165136018294-adktbn0dkrt8qdm9tgbef8udg1920h5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.stustep',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs8DIQjxYZGHAmaMZdwn0RQToxm3C5TpU',
    appId: '1:165136018294:ios:223a27f1dc62f06cfc6857',
    messagingSenderId: '165136018294',
    projectId: 'stustep-4c1ea',
    storageBucket: 'stustep-4c1ea.firebasestorage.app',
    androidClientId: '165136018294-3h92596n21j0v0kqh91hp5jjgm1q4drp.apps.googleusercontent.com',
    iosClientId: '165136018294-adktbn0dkrt8qdm9tgbef8udg1920h5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.stustep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-dCwcS4V2cRToHeRwxF8VyOj2Kf7SOpo',
    appId: '1:165136018294:web:453efc30560fd4b8fc6857',
    messagingSenderId: '165136018294',
    projectId: 'stustep-4c1ea',
    authDomain: 'stustep-4c1ea.firebaseapp.com',
    storageBucket: 'stustep-4c1ea.firebasestorage.app',
  );
}
